# Generated by Django 5.2.6 on 2025-09-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('sweater', 'Sweater'), ('baju', 'Baju'), ('celana', 'Celana'), ('sepatu', 'Sepatu'), ('tas', 'Tas'), ('sleeve', 'Sleeves'), ('kaos kaki', 'Kaos Kaki'), ('lain', 'Lainnya')], default='update')),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
